#!/usr/bin/python

import time as t
import sys

i = 0
while i < 1000:
    i+= 1
    t.sleep(0.01)
    if i < 100:
        print("\tORGANIZANDO pixeles " + str(i))
    elif i < 300:
        print('\033[1;32;40m Comparando frames Algoritmico: Aprobado')
        if i % 4 == 0:
            print("\033[1;31;40m Comparando frames Algoritmico: ERROR")
    elif i < 600:
        print('\t Comparando: #CRA'+ str(i) + str(i+9) + str(i-9)+ str(i*999))
    else:
        print("\tGENERANDO SIMULACION #" + str(i))
print('\n\n ........Listo..... \n')
print('\t####### ERROR DE EXACTITUD: 23% ##########')
print('\t####### PRECISION:  57% ###########')
print("\033[1;31;40m \n\tREPORTE: ALGORITMO FALLIDO\n\n")
